import type { CharacterDef, Element, Region, Weapon, WeaponDef } from '../lib/types';
import game from './game.json';

/** Generated by `npm run sync-data` from gi.yatta.moe. */
export const GAME_DATA_UPDATED: string = game.updated;

export const slug = (name: string) =>
  name
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

/** Loose key for matching names across sources ("RaidenShogun", "raiden_shogun", "Raiden Shogun"). */
export const looseKey = (s: string) =>
  s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]/g, '');

export const BASE_CHARACTERS: CharacterDef[] = game.characters.map((c) => ({
  id: c.id,
  name: c.name,
  nameDe: c.nameDe,
  element: c.element as Element,
  weapon: c.weapon as Weapon,
  rarity: c.rarity as 4 | 5,
  region: c.region as Region,
  avatarId: c.avatarId,
  release: c.release,
  icon: c.icon,
}));

export const WEAPON_DEFS: WeaponDef[] = game.weapons.map((w) => ({
  id: w.id,
  key: w.key,
  name: w.name,
  nameDe: w.nameDe,
  rarity: w.rarity as 1 | 2 | 3 | 4 | 5,
  type: w.type as Weapon,
  icon: w.icon,
}));

export interface ArtifactSetDef {
  id: number;
  name: string;
  nameDe: string;
  maxRarity: number;
  icon: string;
}

export const ARTIFACT_SETS: ArtifactSetDef[] = game.artifactSets;

const setByKey = new Map<string, ArtifactSetDef>();
for (const a of ARTIFACT_SETS) setByKey.set(looseKey(a.name), a);

/** Looks up an artifact set by GOOD key ("GladiatorsFinale"), name or numeric id. */
export function findArtifactSet(keyOrId: string | number): ArtifactSetDef | undefined {
  if (typeof keyOrId === 'number') return ARTIFACT_SETS.find((a) => a.id === keyOrId);
  return setByKey.get(looseKey(keyOrId));
}

const charByKey = new Map<string, CharacterDef>();
for (const c of BASE_CHARACTERS) {
  charByKey.set(looseKey(c.name), c);
  if (c.nameDe) charByKey.set(looseKey(c.nameDe), c);
}
// Common aliases used by other tools (GOOD keys, paimon.moe ids, in-game short names).
const ALIASES: Record<string, string> = {
  raiden: 'raiden-shogun',
  shogunraiden: 'raiden-shogun',
  kazuha: 'kaedehara-kazuha',
  ayaka: 'kamisato-ayaka',
  ayato: 'kamisato-ayato',
  kokomi: 'sangonomiya-kokomi',
  itto: 'arataki-itto',
  sara: 'kujou-sara',
  heizou: 'shikanoin-heizou',
  shinobu: 'kuki-shinobu',
  childe: 'tartaglia',
  mizuki: 'yumemizuki-mizuki',
  scaramouche: 'wanderer',
};
const byId = new Map(BASE_CHARACTERS.map((c) => [c.id, c]));

export function findCharacter(name: string): CharacterDef | undefined {
  const k = looseKey(name);
  // "TravelerAnemo" (GOOD) etc. – but not the weapon "Traveler's Handy Sword".
  if (/^traveler(anemo|geo|electro|dendro|hydro|pyro|cryo)?$/.test(k) || k === 'aether' || k === 'lumine') return byId.get('traveler');
  return charByKey.get(k) ?? byId.get(ALIASES[k] ?? '');
}

const weaponByKey = new Map<string, WeaponDef>();
for (const w of WEAPON_DEFS) {
  weaponByKey.set(looseKey(w.name), w);
  if (w.nameDe) weaponByKey.set(looseKey(w.nameDe), w);
}
const weaponById = new Map(WEAPON_DEFS.map((w) => [w.id, w]));

export function findWeapon(nameOrId: string | number): WeaponDef | undefined {
  if (typeof nameOrId === 'number') return weaponById.get(nameOrId);
  return weaponByKey.get(looseKey(nameOrId));
}

/** Display name in the UI language (game data names are English). */
export function localName(name: string, lang: string): string {
  if (lang !== 'de') return name;
  const c = findCharacter(name);
  if (c?.nameDe) return c.nameDe;
  return findWeapon(name)?.nameDe ?? name;
}

export const characterByAvatarId = (id: number) => BASE_CHARACTERS.find((c) => c.avatarId === id);

/** Icon CDN (Project Amber). Images are only referenced, never bundled. */
export const iconUrl = (icon?: string) =>
  icon ? `https://gi.yatta.moe/assets/UI/${icon.startsWith('UI_RelicIcon') ? 'reliquary/' : ''}${icon}.png` : undefined;

/**
 * 5★ characters in the standard pool, with the date they joined it (ms).
 * Losing the 50/50 means getting one of these on a character event banner.
 * Dates mark the end of their own limited banner, so earlier pulls count as wins.
 */
export const STANDARD_FIVE_STARS: Record<string, number> = {
  diluc: 0,
  jean: 0,
  keqing: 0,
  mona: 0,
  qiqi: 0,
  tighnari: Date.UTC(2022, 8, 10),
  dehya: Date.UTC(2023, 2, 22),
  'yumemizuki-mizuki': Date.UTC(2025, 2, 5),
};

export const ELEMENTS: Element[] = ['pyro', 'hydro', 'anemo', 'electro', 'dendro', 'cryo', 'geo'];
export const WEAPONS: Weapon[] = ['sword', 'claymore', 'polearm', 'bow', 'catalyst'];
export const REGIONS: Region[] = [
  'mondstadt',
  'liyue',
  'inazuma',
  'sumeru',
  'fontaine',
  'natlan',
  'nodkrai',
  'snezhnaya',
  'other',
];
